var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var cors=require('cors');
var loginaction=require('./routes/loginaction');
var districtaction=require('./routes/districtaction');
var districtview=require('./routes/districtview');  
var deletedistrict=require('./routes/deletedistrict');
var dlocation=require('./routes/dlocation');
var locationaction=require('./routes/locationaction');
var categoryaction=require('./routes/categoryaction');
var categoryview=require('./routes/categoryview');  
var deletecategory=require('./routes/deletecategory');
var getCategorydetailsbyid =require('./routes/getCategorydetailsbyid');
var getDistrictdetailsbyid =require('./routes/getDistrictdetailsbyid');
var getLocationdetailsbyid =require('./routes/getLocationdetailsbyid');
var deletelocation=require('./routes/deletelocation');
var locationview=require('./routes/locationview');
var updatelocation=require('./routes/updatelocation');
var updatedistrict=require('./routes/updatedistrict');
var updatecategory=require('./routes/updatecategory');
var ddistrict=require('./routes/ddistrict');
var upload=require('./routes/upload');
var sregisteraction=require('./routes/sregisteraction');
var cregisteraction=require('./routes/cregisteraction');
var wcregisteraction=require('./routes/wcregisteraction');
var wcview=require('./routes/wcview');
var pregisteraction=require('./routes/pregisteraction');
var pview=require('./routes/pview');
var deletep=require('./routes/deletep');
var getProductdetailsbyid=require('./routes/getProductdetailsbyid');
var updatep=require('./routes/updatep');
var sview=require('./routes/sview');
var deletes=require('./routes/deletes');
var deletewc=require('./routes/deletewc');
var accepts=require('./routes/accepts');
var getStockdetailsbyid=require('./routes/getStockdetailsbyid');
var updatestock=require('./routes/updatestock');
var wcsview=require('./routes/wcsview');
var assigning=require('./routes/assigning');
var productbycategory=require('./routes/productbycategory');
var wcshops=require('./routes/wcshops');
var markCollected=require('./routes/markCollected');
var wcassign=require('./routes/wcassign');
var markcancelled=require('./routes/markcancelled');
var getwcdetails=require('./routes/getwcdetails');
var getshopdetails=require('./routes/getshopdetails');
var productbypid=require('./routes/productbypid');
var Addtocart=require('./routes/Addtocart');  
var cpview=require('./routes/cpview');  
var pdata=require('./routes/pdata');
var deletecp=require('./routes/deletecp');
var updatepdetails=require('./routes/updatepdetails');
var plocationadd=require('./routes/plocationadd');  
var cpviewt=require('./routes/cpviewt');
var finalpayment=require('./routes/finalpayment');
var addressview=require('./routes/addressview');
var Buy=require('./routes/Buy');
var cartnum=require('./routes/cartnum');
var orderview=require('./routes/orderview');
var senttodel=require('./routes/senttodel');
var ordermview=require('./routes/ordermview');
var customerorderview=require('./routes/customerorderview');
var assiview=require('./routes/assiview');
var removeass=require('./routes/removeass');
var getshopdetailsbyid=require('./routes/getshopdetailsbyid');
var getwdetails=require('./routes/getwdetails');
var getwstatus=require('./routes/getwstatus');
var getstatusview=require('./routes/getstatusview');
var wcdd=require('./routes/wcdd');
var wctodayview=require('./routes/wctodayview');
var admindashboard=require('./routes/admindashboard');
var collectionrequest=require('./routes/collectionrequest');
var collectionrequestview=require('./routes/collectionrequestview');
var collectionrequestreply=require('./routes/collectionrequestreply');
var collectionrequestbyowner=require('./routes/collectionrequestbyowner');
var shopownercollectedtoday=require('./routes/shopownercollectedtoday');
var shopownercollectionhistory=require('./routes/shopownercollectionhistory');
var getadminprofile=require('./routes/getadminprofile');
var updateadminprofile=require('./routes/updateadminprofile');
var getcustomerprofile=require('./routes/getcustomerprofile');
var updatecustomerprofile=require('./routes/updatecustomerprofile');
var getshopownerprofile=require('./routes/getshopownerprofile');
var updateshopownerprofile=require('./routes/updateshopownerprofile');
var getcollectorprofile=require('./routes/getcollectorprofile');
var updatecollectorprofile=require('./routes/updatecollectorprofile');
var getownerdiscount=require('./routes/getownerdiscount');

var app = express();

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
global.__basedir = path.resolve(path.dirname('')); 

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use(cors());
app.use('/loginaction',loginaction);
app.use('/districtaction',districtaction);
app.use('/districtview',districtview);
app.use('/deletedistrict',deletedistrict);
app.use('/dlocation',dlocation);
app.use('/locationaction',locationaction);
app.use('/categoryaction',categoryaction);
app.use('/categoryview',categoryview);
app.use('/deletecategory',deletecategory);
app.use('/getCategorydetailsbyid',getCategorydetailsbyid);
app.use('/getDistrictdetailsbyid',getDistrictdetailsbyid);
app.use('/getLocationdetailsbyid',getLocationdetailsbyid);
app.use('/deletelocation',deletelocation);
app.use('/locationview',locationview);
app.use('/updatelocation',updatelocation);
app.use('/updatedistrict',updatedistrict);
app.use('/updatecategory',updatecategory);  
app.use('/ddistrict',ddistrict);
app.use('/upload',upload);
app.use('/sregisteraction',sregisteraction);
app.use('/cregisteraction',cregisteraction);
app.use('/wcregisteraction',wcregisteraction);
app.use('/wcview',wcview);
app.use('/pregisteraction',pregisteraction);
app.use('/pview',pview);
app.use('/deletep',deletep);
app.use('/getProductdetailsbyid',getProductdetailsbyid);
app.use('/updatep',updatep);
app.use('/sview',sview);
app.use('/deletes',deletes);
app.use('/deletewc',deletewc);
app.use('/accepts',accepts);
app.use('/getStockdetailsbyid',getStockdetailsbyid);
app.use('/updatestock',updatestock);
app.use('/wcsview',wcsview);
app.use('/assigning',assigning);
app.use('/productbycategory',productbycategory);
app.use('/wcshops',wcshops);
app.use('/markCollected',markCollected);
app.use('/wcassign',wcassign);
app.use('/markcancelled',markcancelled);
app.use('/getwcdetails',getwcdetails);
app.use('/getshopdetails',getshopdetails);
app.use('/productbypid',productbypid);
app.use('/Addtocart',Addtocart);
app.use('/cpview',cpview);
app.use('/pdata',pdata);
app.use('/deletecp',deletecp);
app.use('/updatepdetails',updatepdetails);
app.use('/plocationadd',plocationadd);
app.use('/cpviewt',cpviewt);
app.use('/finalpayment',finalpayment);
app.use('/addressview',addressview);
app.use('/Buy',Buy);
app.use('/cartnum',cartnum);
app.use('/orderview',orderview);
app.use('/senttodel',senttodel);
app.use('/ordermview',ordermview);
app.use('/customerorderview',customerorderview);
app.use('/assiview',assiview);
app.use('/removeass',removeass);
app.use('/getshopdetailsbyid',getshopdetailsbyid);
app.use('/getwdetails',getwdetails);
app.use('/getwstatus',getwstatus);
app.use('/getstatusview',getstatusview);
app.use('/wcdd',wcdd);
app.use('/wctodayview',wctodayview);
app.use('/admindashboard',admindashboard);
app.use('/collectionrequest',collectionrequest);
app.use('/collectionrequestview',collectionrequestview);
app.use('/collectionrequestreply',collectionrequestreply);
app.use('/collectionrequestbyowner',collectionrequestbyowner);
app.use('/shopownercollectedtoday',shopownercollectedtoday);
app.use('/shopownercollectionhistory',shopownercollectionhistory);
app.use('/getadminprofile',getadminprofile);
app.use('/updateadminprofile',updateadminprofile);
app.use('/getcustomerprofile',getcustomerprofile);
app.use('/updatecustomerprofile',updatecustomerprofile);
app.use('/getshopownerprofile',getshopownerprofile);
app.use('/updateshopownerprofile',updateshopownerprofile);
app.use('/getcollectorprofile',getcollectorprofile);
app.use('/updatecollectorprofile',updatecollectorprofile);
app.use('/getownerdiscount',getownerdiscount);

module.exports = app;
